### ISSUE TITLE
Fix the build pipeline

### ISSUE THREAD

**Issue by sebinside** [PalladioSimulator/Palladio-Addons-DataFlowConfidentiality-Analysis#19]
After #4, there still remain some problems with the build and testing. This shall be investigated in order to enable automatic test execution.

**Comment by Nicolas-Boltz** [comment]
There was a misconfigured build.properties in the testmodels bundle. Due to this error, the activator was not built and could consequently not be found by tycho. This and an error with the feature definition have now been fixed.
The pipeline should now run successfully and deploy proper artifacts to our update site.
