### ISSUE TITLE
Investigate custom node type for branches

### ISSUE THREAD

**Issue by sebinside** [PalladioSimulator/Palladio-Addons-DataFlowConfidentiality-Analysis#37]
In the current version, branches are rolled out but the resulting action sequences do not show the points where branches actually happened. Similar to generating a node at the start of every SEFF, we should think about generating a node at the start of every BranchTransition. This would simplify the analysis of data flows.

**Comment by Entenwilli** [comment]
As of now, the analysis already inserts a `SEFFActionSequenceElement` for the Start of an Branch Transition. If you take a look at the first sequence of the BranchingOnlineShop model, the current analysis gives this result:
```
...
SEFFActionSequenceElement (Beginning buy, _nGp9cITjEeywmO_IpTxeAg)) <---- Call of the SEFF Method buy()
SEFFActionSequenceElement (Beginning buy, _vpIdQdv1EeyYrpd_1AtxSw)) <----- Incorrectly labeled/named SEFF Start Action of the BranchTransition
CallingSEFFActionSequenceElement / calling (SaveInventoryCall, _DX-mcNv2EeyYrpd_1AtxSw))
...
```

Currently it would be possible to determine, whether an SEFF Start Action is present because of an ExternalCall or Branch. We could use this information as an attribute of an `SEFFActionSequenceElement` and improve the Console Output of our analysis

**Comment by sebinside** [comment]
Ah, that looks promising. Then it's not a case of a missing element but rather of an unprecise console log.

**Comment by sebinside** [comment]
Discussed solution: Add a method that yields whether the StartAction is inside a branch. And fix `toString()`
