### ISSUE TITLE
Investigate gap in semantics regarding the old Prolog analysis

### ISSUE THREAD

**Issue by sebinside** [PalladioSimulator/Palladio-Addons-DataFlowConfidentiality-Analysis#7]
We hope that there is no major gap in the analysis semantics regarding the older Prolog analysis. However, at least the results differ in some cases when variable usages in data flow sinks are missing in the new analysis. This shall be investigated by comparing the newer TravelPlanner model to [this](https://fluidtrust.github.io/tutorial-ecsa2021/material/) older one.

**Comment by majuwa** [comment]
The current planned analysis does not consider all elements from the previous PROLOG analysis. So far, we only focus on the classical Palladio. Other model elements like indirection or infrastructure calls are not considered. However, this is not in focus for us. In the future, it might be, in that case, we would open a new ticket.
Otherwise, @sebinside and I think that the analysis should have similar behavior as the old PROLOG analysis.
